### ISSUE TITLE
Controller works - Keyboard acts like controller when controller is disconnected

### ISSUE THREAD

**Issue by INsynth** [nefarius/ScpServer#100]
Controller works flawlessly so far, but when I use the keyboard and mouse, I spin really fast in different games or the mouse just flies to parts of the screen. I even uninstalled SCPtookit and I still notice the same thing happening.

**Comment by Jan200101** [comment]
This might not be be SCPServers fault maybe you (or a friend etc.) changed some setting

**Comment by INsynth** [comment]
Okay, I reinstalled SCP and uninstalled it again. All of a sudden, my keyboard magically works now.
No clue what happened, but hey.

**Comment by INsynth** [comment]
Welp, it's back. Here's some context:
After I uninstalled, the issue came back. Then the keyboard turned off randomly and everything was back to normal. I plugged in my PS3 controller for a different game and when I was finished playing, I started spinning uncontrollably, but only once I press a button on the keyboard and move the mouse. I'll reinstall SCP and post logs.

**Comment by INsynth** [comment]
Logs:
http://www.mediafire.com/download/v2c63yie1810i1n/ScpToolkit_Log-Package_1451303339.zip

**Comment by Jan200101** [comment]
Okay i havent read the logs yet (and dont understand all of it yet) but my guess is that you maybe hold the joy stick while unplugging / the driver failed to translate the ps3 controller code to xbox360 controller code and  put it to position 0,0

**Comment by INsynth** [comment]
Hmm might be since the joystick of my controller is iffy at times. Well it's back to normal again, but I'll try to update if anything weird happens. Part of me thinks that I accidentally installed the driver on the keyboard, so I'll just hook-up another usb keyboard and uninstall from there.

**Comment by Jan200101** [comment]
okay
