### ISSUE TITLE
BSOD after Driver Install

### ISSUE THREAD

**Issue by Yadronoff** [nefarius/ScpServer#101]
I'm getting the c9 and d1 code BSOD every time I try to turn on the gamepad after successfully installing an SCP Driver. Something about scpvbus.sys is wrong.
I tried everything that was advised to do when getting these error codes, but it did nothing.
Funny thing is, I had another PS3 controller and it worked just fine, the problems began after windows reinstall and a new pad.
Please, HALP, I'm killing my 3d day in a row, trying to do something about it
Thanks:) 

https://www.dropbox.com/s/1sc0ngen5tgk4rv/Minidump.rar?dl=0
https://www.dropbox.com/s/3djc90jjpuxcfdy/ScpToolkit_Log-Package_Yar_1450802743.zip?dl=0

**Comment by Jan200101** [comment]
So you installed Windows 10 (or any other Windows version) and it stoped working ? hm... have you tried reinstalling it

**Comment by Yadronoff** [comment]
Tried everything. Solved by reinstalling windows again!

**Comment by Jan200101** [comment]
Well thats a way to do it...
