### ISSUE TITLE
Driver for Xbox 360 Controller is removed after restart

### ISSUE THREAD

**Issue by DuskEyed** [nefarius/ScpServer#105]
Running the installer for the Dualshock3 controller, and using the controller is flawless. However, after I restart my computer (Windows 10 64bit) the device labeled "Xbox 360 Controller" that the installer creates, is gone. The scpsettings.exe and scpmonitor.exe do not function and throw errors after a restart.

If needed, I can provide the debug file created by the scpdebug program.

**Comment by 1cup** [comment]
This sounds like a problem with your xbox 360 driver and not scp server.  Make sure these are installed: 
https://www.microsoft.com/hardware/en-US/d/xbox-360-controller-for-windows

**Comment by DuskEyed** [comment]
I don't think that is the issue, seeing as how the controller would not function at all if I did not have this driver installed. (I do)

**Comment by DuskEyed** [comment]
If I run the installer again, the device shows up in the control panel, but consistently gets removed after a restart.

**Comment by Jan200101** [comment]
after a restart open a command promt and write "NET HELPMSG 3521" in it and tell us the results.

**Comment by DuskEyed** [comment]
"The *** service is not started." I'm assuming this means that it's an issue with it starting back up automatically?

**Comment by Jan200101** [comment]
yep go into your services and search for "SCP DSx Service" and change the startup option from 

"Automatically" to "Automatically (Delayed Start)"
that should fix it

**Comment by DuskEyed** [comment]
So I used the Services application to start it manually, and immediately heard it connect my controller. So, that was the issue, I'm going to set it to a delayed start like you said and see if that works.

**Comment by Jan200101** [comment]
It should I did for me. The Problem is that the Service has some kind of error on startup when starting too early which kills it.
If it still wont work then I would try making batch for it and starting the batch when you want to use your  controller.

**Comment by DuskEyed** [comment]
Having it delay the startup worked out, thanks a ton.

**Comment by Jan200101** [comment]
no problem
