### ISSUE TITLE
ScpToolkit Driver Installer

### ISSUE THREAD

**Issue by Ninja92** [nefarius/ScpServer#107]
"ScpToolkit Driver Installer" doesn't do anything. It won't load, I've tried everything. Please tell me what i might try to do.
![image](https://cloud.githubusercontent.com/assets/16446567/12007501/e0702bf2-ac07-11e5-809a-68cd8f3e9afa.png)

(I'm Italian, in my screenshot you can see that I open the installer as administrator and nothing appears in task manager)

Windows 8.1

**Comment by Jan200101** [comment]
Thats New. What windows are you using ? It looks odd to me

**Comment by jfchevrette** [comment]
Same here. Had to reinstall Windows 10 today and after a fresh install I installed ScpServer and the driver installed doesn't do anything.

**Comment by Ninja92** [comment]
As I said, Windows 8.1

**Comment by jfchevrette** [comment]
I have the try icon which only has the "Exit" option in the menu. Double-clicking it doesn't do anything either.

Starting the ScpToolkit Settings Manager returns an Unexpected Error: Initialization of SCPSettings.MainWindow threw an exception"

**Comment by jfchevrette** [comment]
Rerunning ScpToolkit_Setup.exe told me I had to install a component (see screenshot). However I'm 100% sure that when installing initially, that component was marked as "Skip" by default so I chose not to change it.

Everything works fine after re-running setup and installing the missing dependency

**Comment by Ninja92** [comment]
I got all of the components and nothing works for me. I don't know what to do. I succesfully installed on my laptop, but I need to use my controller on this computer.

**Comment by antisparkles99** [comment]
Try uninstalling everything, then installing the latest visual c++, then installing everything again, using ScpToolkit Driver Installer , then run ScpMonitor.exe

**Comment by antisparkles99** [comment]
Same happened for me too, the interface is made using C++ I guess, installing and everything worked fine here

**Comment by Ninja92** [comment]
I've done what you said, all i get is this. Look at the screenshot.
![image](https://cloud.githubusercontent.com/assets/16446567/12010074/ae6a2006-ac96-11e5-9953-e35dd5c4deaa.png)

I translate for you.
In Italian "Segnalazione problemi di Windows" means "Windows Error Reporting"

**Comment by Ninja92** [comment]
I tried a lot of uninstalling and reinstalling, i still get the same error. What can I do?

**Comment by nefarius** [comment]
When Windows Error Reporting kicks in it means the program has crashed and can't recover from it. You'll find additional info about the crash in the Windows Event Log (google). My interface is in German but you should be able to find the entries by following this screenshot:

![](http://nefarius.at/wp-content/uploads/2013/12/28-12-_2015_21-06-30.png)

**Comment by Ninja92** [comment]
Thanks for your support, please tell me if you need translations from Italian to English. Do you need more informations?
![image](https://cloud.githubusercontent.com/assets/16446567/12033713/960e2dd6-ae26-11e5-94ea-625b2b476d2b.png)
![image](https://cloud.githubusercontent.com/assets/16446567/12033715/a31b33f2-ae26-11e5-9eb1-99e7d85a1b94.png)

**Comment by nefarius** [comment]
@Ninja92 [please try the latest stable release](../releases/tag/v1.6.229.15365); I added some more error handling to the Driver Installer start-up. Also please Install the `ScpToolkit Debug Info Collector` component, run it after you encountered an error, and follow its instructions.

**Comment by Ninja92** [comment]
![image](https://cloud.githubusercontent.com/assets/16446567/12064216/86c5b5cc-afbd-11e5-9361-e8d596eb567a.png)
![image](https://cloud.githubusercontent.com/assets/16446567/12064218/a2544470-afbd-11e5-9955-348541ab9762.png)

**Comment by nefarius** [comment]
Damn, what's happening on your machine @_@ please zip up and attach the files in the `Logs` folder here for my review.

**Comment by Ninja92** [comment]
Please download from my dropbox.
https://www.dropbox.com/s/w4v20p6kxvpy2ji/Logs.zip?dl=0
Github keeps saying that this is not a .zip file >.>
(I'm really grateful for your help, Happy New Year)

**Comment by nefarius** [comment]
Happy new year to you too :)

That's weird; is `C:\ScpToolkit\` your install path? Does this file `C:\ScpToolkit\libwdi\amd64\libwdi.dll` exist on your side?

**Comment by Ninja92** [comment]
![image](https://cloud.githubusercontent.com/assets/16446567/12071073/1ba1eff0-b098-11e5-9b35-8c5fd6d091c2.png)

**Comment by nefarius** [comment]
Do you have UAC disabled? Have you used this install folder with older versions too? Did you try to uninstall, fully delete the folder by hand and do a fresh install?

**Comment by Ninja92** [comment]
I uninstalled and did a fresh install 2 times. Now for the UAC, do you mean this?
![screenshot_20160101150157](https://cloud.githubusercontent.com/assets/16446567/12071082/b2c4251a-b098-11e5-8a50-0d6e6515da78.png)

**Comment by nefarius** [comment]
Did you **delete** the folder after uninstall? Yes, I mean this setting. I'd stick to Microsofts recommendation and set this to its default level or else it might have weird side effects with programs requiring administrator rights. From the logs you submitted I assume a file permission problem.

**Comment by Ninja92** [comment]
I'll set to default level, unistall, delete the folder, reinstall, and try.

**Comment by Ninja92** [comment]
Fresh install, still the same. Now I have only 1 file in the log folder.
https://www.dropbox.com/s/yvopb66c0e2jooi/ScpDsxInstaller_Ninja.log.xml.zip?dl=0

**Comment by nefarius** [comment]
What path did you install it to?

**Comment by Ninja92** [comment]
Oh god. Wait a second, this time i did a serious mistake.

**Comment by Ninja92** [comment]
Do you want to continue this thread on skype? Only text no voice.

**Comment by nefarius** [comment]
[I created a chat room on Github](https://gitter.im/nefarius/ScpServer), wanna switch over there?

**Comment by Ninja92** [comment]
Nefarius i have some news, please enter in the chat again.

**Comment by nefarius** [comment]
Nice! What was the problem?

**Comment by Ninja92** [comment]
I don't know, i just did a reboot.

**Comment by nefarius** [comment]
Well good for you! Have fun playing! :)
