### ISSUE TITLE
Controller is only working in the XBOX game hub but not anywhere else?

### ISSUE THREAD

**Issue by rosterx** [nefarius/ScpServer#109]
I installed everything correctly, I'm pretty sure. I start the SCPtoolkit server and it seems fine, no errors. If I press my PS button it will pull up the GameHub for xbox or windows 10 or whatever it is and I can use the controller to navigate it. But I can't move my mouse with it or anything. What do I do?

**Comment by nefarius** [comment]
What do you mean by "you can't move your mouse with it"? Did you try it with a game? Or `joy.cpl`?

**Comment by rosterx** [comment]
@nefarius Shouldn't I be able to move my mouse freely around my screen with the controller? I tried it with the game too but it didn't work. I'm trying to play Dark Souls on steam. The controller only works with the xbox app so far..Maybe I need to link the game to the xbox app somehow? And what is joy.cpl?

**Comment by rosterx** [comment]
@nefarius Actually it is working, I just launched the game from the xbox app and it worked. Thanks for this software! Really easy install and works great :)

**Comment by nefarius** [comment]
Glad to hear, have fun gaming!
