### ISSUE TITLE
Donation system?

### ISSUE THREAD

**Issue by jclevesque** [nefarius/ScpServer#122]
I never could make sense of all the previous SCP / Motioninjoy / Xinput *documentation* scattered over the internet in different forums (if we can call forum posts documentation). I want to thank you for making a cleanly documented and working github project (and all the efforts required to get to this state). Would you be inclined to setup some kind of donation system? I'm not super rich - I'm thinking of donating something around 10$ (I like to think of it as paying you a beer for your efforts), but perhaps others will join in!

**Comment by nefarius** [comment]
Thanks for considering a donation :) [I set a PayPal button up on my main forum thread here](http://forums.pcsx2.net/Thread-ScpToolkit-XInput-Wrapper-aka-ScpServer-Reloaded?pid=474175#pid474175).

**Comment by jclevesque** [comment]
Thanks, done!

**Comment by nefarius** [comment]
Thank you kindly :)
