### ISSUE TITLE
Somehow differentiating libusbK driver name from that of the previous one

### ISSUE THREAD

**Issue by mirhl** [nefarius/ScpServer#124]
Every now and then I find myself in need of normal bt connectivity, so I have to reinstall windows own "Generic Bluetooth Radio" driver. 
Unfortunately when I open "update driver" window in device manager I end up with two identically named drivers. Could this be slightly renamed for easiness?

On a side and probably OT note: is there any way for Ds3 service not to keep bluetooth device always "opened" so that I don't have to stop it to replace this driver without rebooting/replugging receiver?
Or is "constant monitoring" required by Dualshock special querying/connection?

ps: I swear this is the last of my nitpicked bug report.

**Comment by nefarius** [comment]
Sorry, name can't be changed since that's a `libwdi` thing. Service keeps the dongle occupied since it acts as the Bluetooth stack and has to respond to connection requests.

**Comment by mirhl** [comment]
@nefarius It's not to be a pain in the ass, but libwdi dev said it's already possible to change driver name.
