### ISSUE TITLE
Mouse no longer works after a force installation.

### ISSUE THREAD

**Issue by Kongk4** [nefarius/ScpServer#125]
I'm on Windows 10. After doing the normal install my controller neither worked nor was detected by the moniter. So I went back to the wiki guide and it said that on 10 I should use the force install check. I checked that along with a couple of boxes I didn't before (thinking they may have been things that I needed), one of them being named OM. 

After clicking install, I noticed it was taking far longer than it should then I noticed I couldn't see or move my mouse. I thought my PC crashed or something, so I turned it off and turned it back on. It still doesn't show up. I looked at the connected devices, learned that it's name was OM and that my PC considers it connected yet it doesn't work.

Did force installing mess up my mouse driver? As much as I would like to know why my PS3 was detected, I would rather know right now how to get my wired mouse to work again.

Any idea on how do I fix this?

PS: I don't have motion joy.

Update: I got another mouse to work. Now the question is why did checking the mouse box destroy my last mouse and how come my PS3 controller still doesn't work.

**Comment by nefarius** [comment]
Since you told the program to replace your mouses driver... what did you expect to happen? Revert the changes by hand in Windows Device Manager and revert to the correct HID driver. Be more careful next time; randomly checking boxes without knowing the consequences is... yeah.
