### ISSUE TITLE
Request: Update notification

### ISSUE THREAD

**Issue by blubbsy** [nefarius/ScpServer#132]
Would be nice if the SCP server could check periodically (once per month? on startup?) if there is an update of the software and show then a notification in the windows notification center.

blubbsy

**Comment by nefarius** [comment]
Your wish will be granted!

**Comment by nefarius** [comment]
Done; check out the latest release :)

**Comment by PLYoung** [comment]
How do I turn this off or even auto-updates for that matter?

**Comment by blubbsy** [comment]
I think its not necessary to check for updates each time when there is an internet connection or when you turn on the machine (even from standby). Maybe once per month is enough? or at least that the popup does not show up when the version is up to date.

**Comment by goblinpope** [comment]
I just discovered (and not by going through the code) that the updater is controlled with the Windows task schedule. Just go in and edit it to your liking or disable/remove it altogether.

**Comment by bdefore** [comment]
@goblinpope can you elaborate? i couldn't find it in Schedule Tasks of Windows 10.

also, the updater does should be removed when uninstalling. presumably there's nothing to update?

**Comment by deefo0** [comment]
@bdefore I found a task call "updater" in the main Task Scheduler Library folder (not under Microsoft or any task subfolders).
