### ISSUE TITLE
Compile from source: ScpVBus.vcxproj : error  : The imported project "ScpVBus.props" was not found.

### ISSUE THREAD

**Issue by gjveron** [nefarius/ScpServer#17]
hi, i'm getting this while compiling from source using ScpServer.sln 

Compile from source: ScpVBus.vcxproj : error  : The imported project "ScpVBus.props" was not found.

it could be that something is missing from source?

**Comment by nefarius** [comment]
Oooops, my bad! Added the missing file to the repository, thanks for reporting!
