### ISSUE TITLE
How to add new, tested, working devices to the list?

### ISSUE THREAD

**Issue by Awebb** [nefarius/ScpServer#20]
Hello!

I successfully tested a new device ID and want it added to the list (so I won't have to recompile it every time). Where should I do this? Do you just want a pull request for the ini?

**Comment by Awebb** [comment]
Now I feel like an idiot, the device I tested is in your sources, but I only searched the original sources for the ID. The matter is solved for me for now, but I'm still uncertain about the proper way to report tested devices.

**Comment by nefarius** [comment]
A pull request will do the trick!
