### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Kamui-Solo** [nefarius/ScpServer#37]
Please build new release or write readme how to do it please.

**Comment by nefarius** [comment]
You're seriously opening up an issue because I'm not releasing updates fast enough? I'll put one up when I think it's ready. A how-to-build is also coming up soon.

**Comment by Dorque** [comment]
I believe you just need VIsual Studio (2013 I believe) to build this. Nothing too fancy. Also need to know how to use Git.
