### ISSUE TITLE
Add a device to the driver package?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [nefarius/ScpServer#38]
This device works, its just not added to the inf.
USB\VID_0489&PID_E031

**Comment by nefarius** [comment]
And the device is... what?

**Comment by BiatuAutMiahn** [comment]
BCM20702

**Comment by nefarius** [comment]
Ah I see, have a look into `ScpControl.ini` :)

**Comment by BiatuAutMiahn** [comment]
cool, thx.

**Comment by nefarius** [comment]
New release has the ability to let the user chose which devices to install.
