### ISSUE TITLE
BT 2.1 + EDR dongle not working correctly

### ISSUE THREAD

**Issue by CookiePLMonster** [nefarius/ScpServer#42]
Are there any other requriements (other than being at least 2.0 the BT dongle has to meet in order to work correctly with SCP? The 2.0 + EDR dongle I bought specifically for SCP seems to malfunction, and its broken-ness actually differs betweeen Scarlett's version and your builds:

- In Scarlett's newest version, the controller pairs yet SCP never ever receives any data
- In your version, the behaviour is purely random - sometimes all buttons will work, albeit without pressure sensitivity. Sometimes, only analog sticks work and the other buttons are stuck on some junk values

Seems like you have enhanced logging a good bit, so are there any means of logging this more efficiently? In Scarlett's build I had to go through a shitton of breakpoints to detemine my old dongle (which was on compat list but turns out it wasn't 2.0) is not compatible.

The pad is a legimate DualShock 3 - no possibility of it being a knockoff, since it was bundled with a PS3.

Dongle in question (do note its VID is listed as compatible):
http://www.4world.pl/categories/product/34/637

**Comment by nefarius** [comment]
Is this still an issue?
