### ISSUE TITLE
PS Home / Guide button: Open Steam?

### ISSUE THREAD

**Issue by berserkwarwolf** [nefarius/ScpServer#46]
I couldn't make it work, so I assume it's not implemented.

Feature request:
Press PS Home and make it work like the guide button on the 360 controller: Open Steam BPM.

Thanks, I love it!

**Comment by nefarius** [comment]
Hi,

it **is** implemented, my Instance of Steam opens in Big Picture Mode just fine!

**Comment by fernandofj** [comment]
If you are using Windows 10, probably it is capturing the button press for the Xbox app and not passing it to Steam. Disabling Windows' DVR may help: https://steamcommunity.com/discussions/forum/1/530645961936632430/#c530646080864378603

**Comment by nefarius** [comment]
Since this is an "issue" with Windows 10 in itself I'm closing this one.
