### ISSUE TITLE
Not an issue, but wanted to say thanks. :)

### ISSUE THREAD

**Issue by unmog** [nefarius/ScpServer#52]
I was feeling nostalgic and wanted to play some old playstation games on my pc... with a ps3 controller. Went to plug it in and it wasnt recognizing them on the emulator, which was strange considering it worked fine before. I used to be on win7 but upgraded to free to 10. Found MotioninJoy and it wouldnt work, then found out how bad for my computer it might be when googling so immediately uninstalled it. Found your program after going through the rabbithole of forums and links people posted, installed it quickly and without problem, now I can play a playstation game with a playstation controller.

Considering how hard it was because Sony wont simply make some official drivers which is still beyond my realm of comprehension, I wanted to personally thank you for the time and effort you spent so I and others could enjoy such simple pleasures. Im unsure what all else is intended behind your drivers, maybe I can use my playstation controller instead of an xbox all the time. But for what all I wanted to do right now it gives me the warm cuddly feelings to relive some nostalgic games I never was able to fully play before. Really, thanks again, words can't really describe my happiness right now. SUCCESS!

BTW Im bookmarking your link here so I can give it to friends if they have problems with their controllers. I really am lucky I found it, I had no idea what I was looking for and just started googling things and reading forum posts. I hope one day the first google link is this page here instead of that Motioninjoy garbage...

**Comment by nefarius** [comment]
Thank you kindly :)
