### ISSUE TITLE
Memory leak after several hours

### ISSUE THREAD

**Issue by runderscore** [nefarius/ScpServer#54]
I've found that, after several hours of (in)activity, the SCPService suddenly begins consuming vast amounts of memory and CPU power.
![Example](https://cloud.githubusercontent.com/assets/16026653/11415009/c0a352b8-944c-11e5-92be-97b69e5374cd.png)
I can't narrow down when this began to occur, but while I only noticed it originating from SCPService recently, it has been happening for quite some time.

System details follow.
>Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Core i5 2500K
RAM
	16.0GB 
Graphics
	4095MB NVIDIA GeForce GTX 970
Audio
	Creative X-Fi Audio Processor 

Using a DS2, a DS3 (official), and a USB bluetooth device (BCM20702A0).

**Comment by nefarius** [comment]
Holy sh*t! I will investigate, thanks for reporting!

**Comment by nefarius** [comment]
I fixed it in the latest pre-release, stable one coming up next, thanks again for reporting!

**Comment by Sir-Joel** [comment]
I know this thread is closed, but I'm experiencing the same issue with the most recent release.
![scp high memory](https://cloud.githubusercontent.com/assets/18381502/14411509/2e3eb8e0-ff18-11e5-8b44-7bbf2ed53e31.PNG)

**Comment by charlesmilette** [comment]
What is the version given in the control panel?

**Comment by Sir-Joel** [comment]
It says version 1.6.238.16010. I'm going to give that beta that was released today a shot though. I'll see if it exhibits the same issue.
