### ISSUE TITLE
ScpServer.exe spawns many threads and has high CPU usage.

### ISSUE THREAD

**Issue by ActuallyDidIt** [nefarius/ScpServer#57]
Running the current beta on Windows 7 shows 528 threads and constantly uses about 5-7% CPU. Is this expected behavior?

**Comment by TheHardew** [comment]
On optimized beta I have 10-15% cpu and I think it's stuck in some thread-adding loop - it adds 2 threads every seconds, now I have 659 of 'em. If I disconnect my ds3 it stops and cpu usage is 0%.

**Comment by OptimisedFun** [comment]
I have this too; i7 6700K. Hits ~80% cpu, thousands of threads within a second and stays there. It *works* fine but I'm sure it shouldn't be doing that.

**Comment by Cauterite** [comment]
The situation seems to have greatly improved now; since I updated to v1.6.186.15342-BETA, the service is eating only a few percent of CPU cycles and sitting at around 20 threads.

**Comment by nefarius** [comment]
Good to know, thanks for your feedback!

**Comment by nefarius** [comment]
[Got fixed in this release.](../releases/tag/v1.6.186.15342-BETA)
