### ISSUE TITLE
Controls get stuck with latest stable and beta

### ISSUE THREAD

**Issue by Keefaetana** [nefarius/ScpServer#59]
The latest stable and beta builds seem to have a big regression in them. When playing a game, the controls are responsive at first, but after about half a minute the controls get "stuck". A few seconds after that the controller starts vibrating for several seconds straight. When it stops vibrating, the controls are responsive for about 10-15 seconds again. Then they get stuck again and after a few seconds the controller starts vibrating again. That repeats over and over again. I tried uninstalling the latest versions and downgraded to the last stable before the current one and the controller works perfectly.

I'm using Windows 10 x64 with all the latest updates and an official DS3 that came with my PS3. GitHub doesn't seem to allow attaching .zip files, so I uploaded my logs here: http://koti.mbnet.fi/nurmip/ScpToolkit_Log-Package_Keefa_1448905405.zip

**Comment by TheHardew** [comment]
Also it's only when wired and disabling rumble doesn't fix it.

**Comment by DSelitskiy** [comment]
Yep, can confirm. Going back one release helped.

**Comment by nefarius** [comment]
The service log is missing in your archive; did you remove it or was it never there?

**Comment by Keefaetana** [comment]
I have not removed anything from the .zip file. I just uploaded it as is and didn't think something could be missing. I'll install the beta again and get the service log for you.

**Comment by MonthOLDpickle** [comment]
@DSelitskiy How do I downgrade?

**Comment by DSelitskiy** [comment]
Do full uninstall. Then grab the previous release from the releases page
and install that instead.

Kind regards,
Dmitry.

---
*Dmitry Selitskiy*

*email*: dmitry@selitskiy.com
*mobile*: +64 (21) 059 8239   ||   *skype*:  dmitry@selitskiy.com
*web*: http://www.selitskiy.com || http://www.thought-wired.com

**Comment by MonthOLDpickle** [comment]
@DSelitskiy I am very new to using github and SCPtoolkit. I don't even see a release folder in https://github.com/nefarius/ScpServer

**Comment by DSelitskiy** [comment]
Here: https://github.com/nefarius/ScpServer/releases and download this
https://github.com/nefarius/ScpServer/releases/tag/v1.6.126.15319

Kind regards,
Dmitry.

---
*Dmitry Selitskiy*

*email*: dmitry@selitskiy.com
*mobile*: +64 (21) 059 8239   ||   *skype*:  dmitry@selitskiy.com
*web*: http://www.selitskiy.com || http://www.thought-wired.com

**Comment by skite2001** [comment]
seems to me, like issue #39
https://github.com/nefarius/ScpServer/issues/39

**Comment by Keefaetana** [comment]
skite2001: Yes, I agree. There are three bugs about the same issue now.

**Comment by MonthOLDpickle** [comment]
@DSelitskiy Welp I can't uninstall old one. I have no clue why. I did follow instructions etc. Service doesn't exist but old version says new one already installed aborting. The install folder is empty...

**Comment by DSelitskiy** [comment]
There's a cleaner tool that comes with the driver, try running that.

Kind regards,
Dmitry.

---
*Dmitry Selitskiy*

*email*: dmitry@selitskiy.com
*mobile*: +64 (21) 059 8239   ||   *skype*:  dmitry@selitskiy.com
*web*: http://www.selitskiy.com || http://www.thought-wired.com

**Comment by Keefaetana** [comment]
The latest beta seems to have fixed the problem for me. Excellent work. Closing the bug now.
