### ISSUE TITLE
Works then ingame stops working...then works again! Repeats =S

### ISSUE THREAD

**Issue by MonthOLDpickle** [nefarius/ScpServer#68]
So just installed it. The controller works awesome when it does, but in Dark Souls 1 I ran into an issue.

At times, it seems like when I get hit or something the controls get stuck so I am either moving without being able to stop or just don't work. After awhile it comes back but then it happens again...

**Comment by Keefaetana** [comment]
That sounds very similar to my earlier bug: https://github.com/nefarius/ScpServer/issues/59

**Comment by MonthOLDpickle** [comment]
@Keefaetana Okay checking it out..hopefully a fix.

**Comment by MonthOLDpickle** [comment]
Fixed with:

https://github.com/nefarius/ScpServer/issues/59#issuecomment-161842545
