### ISSUE TITLE
Does not work with PS3 controller tilt

### ISSUE THREAD

**Issue by CriusMacOldenly** [nefarius/ScpServer#75]
The Motioninjoy PS3 drivers do work with the PS3's tilt controls properly, so I know it is possible.
This driver does not currently work with any of the tilts on the controller.
There does not appear to be any calibration for the tilt either, or at least none I could recognize.
[Controller (XBOX 360 For Windows)_hid-report.dump.txt](https://github.com/nefarius/ScpServer/files/53314/Controller.XBOX.360.For.Windows._hid-report.dump.txt)

**Comment by nefarius** [comment]
Gyroscole and accelerometer aren't implemented yet. Will announce it in the release notes when done.
