### ISSUE TITLE
[LilyPad SCP] Can't config all stick axes. Result in calibration problem.

### ISSUE THREAD

**Issue by skite2001** [nefarius/ScpServer#79]
I cant config the "down" and "right" axes of the L and R -Stick. It happens nothing, if i try to set these to the fitting gui-buttons. can't play this way, because my character turns in circles :(
![lilypad01](https://cloud.githubusercontent.com/assets/16143085/11700421/07aa416c-9eca-11e5-9f4f-2c2e0cb885ee.jpg)
![lilypad02](https://cloud.githubusercontent.com/assets/16143085/11700422/07ad7b98-9eca-11e5-8b2f-53f75e2e8e92.jpg)

**Comment by nefarius** [comment]
Right, you've spotted a bug. I'll work on a fix!

**Comment by nefarius** [comment]
I fixed the issue; playing Metal Gear Solid 3 right now :) Will be included in the next release!

**Comment by skite2001** [comment]
very much thx. and good work
