### ISSUE TITLE
Can't get USB driver to install on ANY computers, running Windows 10

### ISSUE THREAD

**Issue by Ganz-hun** [nefarius/ScpServer#86]
Hello!
I tried to install the BT software on my Windows 10 laptops (Asus K455L, and a first gen. Surfce Pro 128GB), using the bult-in Bluetooth device, and it says WDI_ERROR_OTHER. I also tried a 3rd party USB BT dongle, and it installed fine on my Windows 7 PC, but not on the computers running Windows 10. Unfortunatelly, I couldn't find the debug app, so I attached two screenshoots. I hope it's enough.

![bt_dngl](https://cloud.githubusercontent.com/assets/16275117/11766335/c5132128-a182-11e5-9d5f-07b7784da552.png)
![debug_inf](https://cloud.githubusercontent.com/assets/16275117/11766336/c517147c-a182-11e5-8130-12eb0ae4200f.png)

**Comment by Ganz-hun** [comment]
The new version installed fine :)

**Comment by nefarius** [comment]
Good to know, I'll allow my self to close this issue then :)
