### ISSUE TITLE
SCPServer Windows Service starting shortcut

### ISSUE THREAD

**Issue by Jan200101** [nefarius/ScpServer#92]
I´ve made a EXE (that starts a batch) so you don´t have to restart (or start) the service if it wont start with the computer.
This works on every Version yet.
I would be happy if someone could make a Icon for it.

Sadly some Antivirus (and Browsers) say that it is a Worm/Trojan
See Here [VirusTotal](https://www.virustotal.com/de/file/40e49da12a86a4a93f73d775bfa0b82916492a66fca6ac20676eecf774c9b6d2/analysis/1450466365/)

so I included the Batch code here
[Batch Code](https://www.dropbox.com/s/re2on8eg2un0dxp/SCPService%20Shortcut.txt?dl=0)

Download 
Dropbox doesnt allow Files that could be Viruses :(
[Mediafire](http://www.mediafire.com/download/oul1qqrs5aqq9ef/SCPService+Shortcut.exe)

p.s. nefarius please change the Label to something like Tool

**Comment by nefarius** [comment]
No. Sorry, just no. That's an over-complicated attempt to create a workaround for something that needs to be fixed. There's a reason it's designed as a Windows Service: to start automatically in background. If it doesn't, it has to be troubleshooted and fixed. You didn't even include the source of the executable. **I highly discourage people from using this!**
