### ISSUE TITLE
Windows Service not starting properly

### ISSUE THREAD

**Issue by Jan200101** [nefarius/ScpServer#93]
Everytime I start my computer the SCP DSx Service(Ds3Service) doesnt start / crashed I dont really know what causes this but restarting it fixes it

**Comment by nefarius** [comment]
Look in your Windows Event Log, in the System-Category you should find service-related errors.

**Comment by Jan200101** [comment]
In the System Category ?
Cant find anything there

![2](https://cloud.githubusercontent.com/assets/15076013/11908994/fc05d712-a5e1-11e5-89d7-d9242f4e5507.png)

**Comment by nefarius** [comment]
That's 'cause you filtered on the wrong source. The service itself doesn't log to the Windows Event Log. You need to filter and see what `Service Control Manager` events are there.

**Comment by Jan200101** [comment]
Found it 
![3](https://cloud.githubusercontent.com/assets/15076013/11912685/315f719a-a649-11e5-9797-e62d69882da9.png)

**Comment by nefarius** [comment]
Please try if [this experimental release](../releases/tag/v1.6.208.15353-BETA) fixes the issue.

**Comment by Jan200101** [comment]
It didn´t i looked in the Services and it said it was running but I cannot connect a controller and stoping it over a batch gives the responds "Service is not running"

**Comment by nefarius** [comment]
The window issue is fixed but not release yet. As for your answer on the service: what?

**Comment by Jan200101** [comment]
The Problem isnt fixed same issue

**Comment by nefarius** [comment]
So what does the event log say now?

**Comment by Jan200101** [comment]
The Picture speak for it self
![5](https://cloud.githubusercontent.com/assets/15076013/11913417/540f54d4-a663-11e5-8452-4413a2df8460.png)

**Comment by nefarius** [comment]
I added some time measurements [to this release](../releases/tag/v1.6.212.15353-BETA). Please try this one and submit the log pack after reboot.

**Comment by Jan200101** [comment]
[ScpToolkit_Log-Package_Jan_1450536921.zip](https://github.com/nefarius/ScpServer/files/67507/ScpToolkit_Log-Package_Jan_1450536921.zip)

**Comment by nefarius** [comment]
The logs tell the service is starting within the expected time span; I'm afraid I'm out of ideas...

**Comment by Jan200101** [comment]
hm... I guess I will keep using my Workaround

**Comment by nefarius** [comment]
You could also try to set the service start mode from `Automatic`to `Automatic (Delayed Start)`

**Comment by Jan200101** [comment]
I try that

**Comment by Jan200101** [comment]
Okay it worked i am going to close this then since it isnt needed anymore
